### ISSUE TITLE
Soft platform dependence

### ISSUE THREAD

**Issue by indutny** [node4good/windows-autoconf#4]
Heya!

I'm working on porting gyp.js to duktape. The process so far looks like this:

* build it with `webpack` + `babel`
* provide alternative `bindings`
* compile it together with `duktape`

However, `windows-autoconf` has **hard** dependency on the platform and thus breaks compilation with `webpack`. Is there any reason for having such limitation?

**Comment by refack** [comment]
No, and I tried to make it "independent" with [`SetBindings()`](https://github.com/node4good/windows-autoconf/blob/master/index.js#L66). Code does not make calls to `require` except in fallback situation.
I do have `"os": ["win32"]` in package.json but that's just for hygiene...

**Comment by refack** [comment]
Show me where it "hurts".

**Comment by indutny** [comment]
I was talking about `os` in `package.json`.

**Comment by refack** [comment]
Gone...

**Comment by indutny** [comment]
Thank you!
